"""empty message

Revision ID: c746e47a7ca6
Revises: 
Create Date: 2024-01-08 14:56:34.380979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c746e47a7ca6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amistoso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('esporte', sa.String(length=80), nullable=True),
    sa.Column('curso1', sa.String(length=80), nullable=True),
    sa.Column('curso2', sa.String(length=80), nullable=True),
    sa.Column('Dt_HR', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('amistoso')
    # ### end Alembic commands ###
